spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  datasource:
    url: "jdbc:mysql://localhost:3306/competence_centre?useSSL=false"
    username: "root"
    password: "zano"
  jpa:
    open-in-view: true

server:
  port: 13000