spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  datasource:
    url: "jdbc:mysql://localhost:3306/competence_centre?useSSL=false"
    username: "root"
    password: "zano"
  jpa:
    open-in-view: true

server:
  port: 12000

soap-service:
  person-client:
    name: "CheckPersonService"
    endpoint: "http://www.freewebservicesx.com/freewebservices/CheckSDNBlockedPerson.asmx"
    contextPath: "it.zano.microservices.gen.person"
    authType: "none"
    soapVersion: "1.2"


rest-template:
  bitcoin-price:
    name: "BitcoinService"
    endpoint: "http://api.coindesk.com/v1/bpi/currentprice.json"
  document-service:
    name: "DocumentsService"
    endpoint: "http://localhost:13000/documents/"

observable-process-manager:
  states:
    NOT_OBSERVED:
      timeout: 0
    PUT_DOCUMENT_IN_PROGRESS:
      timeout: 5
    WAITED_IN_PROGRESS:
      timeout: 5
    END:
      timeout: 0
  transitions:
    CREATE:
      from: "NOT_OBSERVED"
      to: "PUT_DOCUMENT_IN_PROGRESS"
    PUT_DOCUMENT_COMPLETED:
      from: "PUT_DOCUMENT_IN_PROGRESS"
      to: "WAITED_IN_PROGRESS"
    WAITED_COMPLETED:
      from: "WAITED_IN_PROGRESS"
      to: "END"
