spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  datasource:
    url: "jdbc:mysql://localhost:3306/competence_centre?useSSL=false"
    username: "root"
    password: "zano"
  jpa:
    open-in-view: true

server:
  port: 12000

soap-service:
  person-client:
    name: "CheckPersonService"
    endpoint: "http://www.freewebservicesx.com/freewebservices/CheckSDNBlockedPerson.asmx"
    contextPath: "it.zano.microservices.gen.person"
    authType: "none"
    soapVersion: "1.2"


rest-template:
  bitcoin-price:
    name: "BitcoinService"
    endpoint: "http://api.coindesk.com/v1/bpi/currentprice.json"
  document-service:
    name: "DocumentsService"
    endpoint: "http://localhost:13000/documents/"

observable-process-manager:
  timeouts:
    NOT_OBSERVED: 0
    PUT_DOCUMENT_IN_PROGRESS: 5
    WAITED_IN_PROGRESS: 5
    END: 0
